=== RomanKarpyn/XML_Task/src/firearm.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <xs:element name="gun">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="firearm" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="origin" type="xs:string"/>
                            <xs:element name="tts">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="carry" type="xs:int"/>
                                        <xs:element name="sightRange" type="xs:double"/>
                                        <xs:element name="shackle" type="xs:string"/>
                                        <xs:element name="optics" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="handy" type="xs:int"/>
                            <xs:element name="materials" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="model" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RomanKarpyn/XML_Task/src/firearm.xml
<?xml version="1.0" encoding="UTF-8"?>
 <gun xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="firearm.xsd">
    <firearm model="Glock 17">
        <origin>Ukraine</origin>
        <tts>
            <carry>1000</carry>
            <sightRange>323.6</sightRange>
            <shackle>false</shackle>
            <optics>true</optics>
        </tts>
        <handy>1</handy>
        <materials>iron</materials>
    </firearm>
    <firearm model="FN Herstal FNP-9">
        <origin>Portugal</origin>
        <tts>
            <carry>500</carry>
            <sightRange>743.6</sightRange>
            <shackle>true</shackle>
            <optics>true</optics>
        </tts>
        <handy>2</handy>
        <materials>iron</materials>

    </firearm>
    <firearm model="Beretta 92FS">
        <origin>England</origin>
        <tts>
            <carry>1000</carry>
            <sightRange>323.6</sightRange>
            <shackle>false</shackle>
            <optics>false</optics>
        </tts>
        <handy>1</handy>
        <materials>iron</materials>
    </firearm>

    <firearm model="QSZ-92">
        <origin>Poland</origin>
        <tts>
            <carry>1500</carry>
            <sightRange>323.6</sightRange>
            <shackle>true</shackle>
            <optics>false</optics>
        </tts>
        <handy>2</handy>
        <materials>tree</materials>
    </firearm>
</gun>
